spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://1.15.188.150:3306/nightfall
    username: root
    password: toor
  redis:
    host: 192.168.80.100
    port: 6379
    database: 0
    password: workANDlive86.
    timeout: 1000
    jedis:
      pool:
#        连接池最大连接数
        max-active: 20
#        连接池最大阻塞等待时间
        max-wait: -1
#        连接池最大空闲连接数
        max-idle: 10
#        连接池最小空闲连接数
        min-idle: 0

server:
  port: 9090
  servlet:
    context-path: /blog

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  config: classpath:log4j2.xml
